
title: "Cameron Wardzala"
tagline: ""
description: "Follow <a href=\"https://micro.blog/camwardzala\">@camwardzala on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/camwardzala\">@camwardzala on Micro.blog</a>."
baseurl: ""
url: "http://camwardzala.com"
markdown: "kramdown"
username: "camwardzala"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Cameron Wardzala"
name: "Cameron Wardzala"
gravatar_hash: "2030baec3517ca4b3d8fb21523509672"
avatar: "https://micro.blog/camwardzala/avatar.jpg"
full_name: "Cameron Wardzala"
bio: ""
twitter_username: "camwardzala"
github_username: "cwardzala"
instagram_username: "camwardzala"
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "2371"